apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  PORT: "5000"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
type: Opaque
stringData:
  REDIS_HOST: "redis"
  MONGO_URI: "mongodb://mongodb:27017/"